"""intial

Revision ID: cfd6db81084b
Revises: 
Create Date: 2025-06-23 19:42:52.105206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd6db81084b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('parents_name', sa.String(length=50), nullable=False),
    sa.Column('parents_user_id', sa.String(length=50), nullable=False),
    sa.Column('student_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_name_id'], ['group_name.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_info')
    op.drop_table('group_name')
    # ### end Alembic commands ###
